### ISSUE TITLE
Missing language string.

### ISSUE THREAD

**Issue by Satton2** [FPtje/darkrpmodification#113]
While translating _english.lua_ I didn't found this string: «You are unable to go AFK. Spam prevention.»
Can it be added to _english.lua_?

**Comment by FPtje** [comment]
It uses a combination of the "unable" phrase and the words `"go AFK"` and `"Spam prevention"`. That's kind of shit to translate because "go AFK" and "Spam prevention" are still English. I've later learned that it's better to translate entire phrases, instead of parts of sentences where you can fill things in. I'm sure there will be plenty of other examples in DarkRP that will make it difficult to translate, but really I cba to change the whole language model around to fix it.

I'll fix this one though
