### ISSUE TITLE
Missing strings, fix requests and translation of the FAdmin.

### ISSUE THREAD

**Issue by Satton2** [FPtje/darkrpmodification#115]
### Missing strings and fix requests
1) After **searching** for illegal weapons that shows us _print name_ of weapons, but after **confiscating** weapons it shows us _code name_ of weapons. Fix, please.
![image](https://user-images.githubusercontent.com/23385240/37044471-9a851bea-2174-11e8-94fc-864b46e4911a.png)
[Sorry for Russian text, I am just translating DarkRP at this moment]
2) Maybe it should be called like «**Usergroup**», but not «**Rank**»?
![image](https://user-images.githubusercontent.com/23385240/37044964-e5252cf2-2175-11e8-97da-1a4e96508fa7.png)
3) Missing string «**Incorrect team**». Example:
![image](https://user-images.githubusercontent.com/23385240/37045857-f34116c8-2177-11e8-8f64-fe8888d6ec26.png)
4) This part is missing to, right? If so: **gamemodes\darkrp\gamemode\modules\f4menu\cl_jobstab.lua** _Line 252_
![image](https://user-images.githubusercontent.com/23385240/37047076-006c8140-217b-11e8-82c0-a297584023b8.png)
### Translation of the FAdmin
_FPtje_, I don't fully understand this «**cba**» in your response to my previous «Issue Ticket» (I don't know how to call it), so can you tell me the full version of it? But, if I understand this right, you what to update whole localization file in the future. Anyway, what about localization of FAdmin? Will it be added to the localization file?
### About my translation
As you already know, I am working on Russian translation for the DarkRP. So, when I will finish the work, can I make a pull request with my localization file (or propose it like new file) to make it official?

**Comment by Satton2** [comment]
Oh, and folders:
1. **garrysmod\gamemodes\darkrp\entities\weapons\weaponchecker\shared.lua** Line **306**
2. **garrysmod\gamemodes\darkrp\gamemode\modules\fadmin\cl_fadmin_darkrp.lua** Line **8**
3. **garrysmod\gamemodes\darkrp\gamemode\modules\police\sv_commands.lua** Lines: **19** _and_ **33**

**Comment by mcNuggets1** [comment]
The functionality of translating fadmin and fspectate would be awesome

**Comment by FPtje** [comment]
I'm afraid I'm not going to do that, though. Gmod projects are on full feature freeze because I'm not as involved as I used to be anymore.

**Comment by Bo98** [comment]
Regarding no. 1, I believe this was due to `wep:GetPrintName()` only being available clientside at the time. This is no longer the case, but there would've been a large number of SWEPs that still had `SWEP.PrintName` under a `if CLIENT` block. It would be worth checking if this is still the case - it would be good if networking could be avoided now.

**Comment by FPtje** [comment]
"cba" means "Can't be arsed". There's a pretty big design mistake in DarkRP's language system. I tried to mix and combine phrases to be more efficient in code. Take this example:

```lua
-- This is in the english.lua file:
unable = "You are unable to %s. %s",
```

You're supposed to fill in the blanks where it says `%s`. Those blanks are filled in by either chat commands, other phrases or even actual English words. Look at your own example:

![img](https://user-images.githubusercontent.com/23385240/37045857-f34116c8-2177-11e8-8f64-fe8888d6ec26.png)

You complained about the `Incorrect Team` bit, but the `agenda` is there hard coded. The solution is to use full phrases, instead of compositions. There would be a lot of duplication in parts of phrases, but that would give the benefit of correct translations. The compositions in `english.lua` *only* work in English. I'm pretty sure there are phrases in there that you cannot translate correctly because the grammars of other languages don't allow the same substitutions as English.

And when I say I cba, I mean I can't be arsed to fix it. You will keep finding English words in your Russian DarkRP. That's a shame, but I'm not fixing it. For this one I actually have a bigger reason than the fact that I'm not as involved in DarkRP anymore, and that is that changing this would invalidate all translations, and that would piss quite a few people off.

**Comment by mcNuggets1** [comment]
I could work together with you, FPtje regarding updates for DarkRP.
Just contact me, I could use some of my free time to help you out (via pull requests etc. or participation), just be sure to tell me what exactly I am allowed to do and what not.

Steam: http://steamcommunity.com/id/daviddorn

**Comment by FPtje** [comment]
No, fixing this would invalidate all translations, and I don't want that.

**Comment by Satton2** [comment]
Well, sad to hear that.

I don't worry about «agenda» and other parts of text that are appears after «You do not have the right job to …», because this is a command, and just because of that this text will be look fine. We are writing this command in chat and know that this is the command that we are just typed. It will be strange _only_ if we will use some context menu with «fast commands», because we don't writing this command in chat.

I know nothing about localizations on other languages, but **almost every** Russian localization is just a localization that was made by some machine (e.g. Google Translator), and this is probably means that we don't have any translator that are well worked on Russian localization for DarkRP. So for Russian translators any fixes will not be a problem. Of course, somewhere can be good examples of Russian localization, but they are not finished _or_ outdated _or_ doesn't exist anymore. But! I will agree that localizations on other languages can be pretty good and any fix can be a problem.

I didn't saw any answer about my last topic. (**About my translation**)

Also, I hope that you will fix issues that I will be probably found in the future.

**Comment by Bo98** [comment]
> I don't worry about «agenda» and other parts of text that are appears after «You do not have the right job to …», because this is a command, and just because of that this text will be look fine. 

We could make the notification say "/agenda" to justify this more - I seem to remember there were other cases of that. But it's a minor detail.

**Comment by Satton2** [comment]
@Bo98 Maybe this slash is a minor detail, but it can improve the understanding of this text for non-English users. If you can do this, then do this.=)

**Comment by mcNuggets1** [comment]
CreateShipment and Split this Shipment should be translateable.
