### ISSUE TITLE
Spawns and Doorgroups not saving

### ISSUE THREAD

**Issue by CarsonJSlane** [FPtje/darkrpmodification#168]
I have been having troubles with the spawns and door groups not saving on restart, I have updated the darkrpmodification about an hour before this post but still having troubles. There is no error in console. Please help if you can

**Comment by FPtje** [comment]
This is typically due to either of two reasons:
- An addon that returns a value in the InitPostEntity hook. 
- There is an error in your DarkRP modifications that prevents DarkRP from loading properly. In this case you might not see an error in your own console, but you should see an error in the server console.

This is definitely not an issue in DarkRP or the darkrpmod itself. The best thing you can do is:

- Look in the _server_ error log
- Remove addons until you find out which one is causing your issue.
