### ISSUE TITLE
PocketBlacklist in settings.lua not doing anything

### ISSUE THREAD

**Issue by Jernee** [FPtje/darkrpmodification#175]
Whenever I add anything to the pocketblacklist table it doesn't get added to the server.

**Comment by FPtje** [comment]
I'm afraid I cannot reproduce this. I tested it by doing the following:

- On a clean DarkRP, start a game
- Try to pocket money (`spawned_money`). This works
- Edit darkrpmodification, in PocketBlacklist, add the following line:
  ```lua
     ["spawned_money"] = true,
  ```
- Restart the game
- Try to pocket some money. This no longer works because I added it to the blacklist.


I can only conclude that there is some user error. Without knowing more about your situation, I can only give the following generic advise:

- Make sure there is no other addon that sets the PocketBlacklist
- Please check your server for errors, either on startup or during gameplay
- Make sure the entry in the PocketBlacklist table is correct. Specifically you need to use the classname of an entity. Otherwise it won't work

**Comment by Jernee** [comment]
> I'm afraid I cannot reproduce this. I tested it by doing the following:
> 
>     * On a clean DarkRP, start a game
> 
>     * Try to pocket money (`spawned_money`). This works
> 
>     * Edit darkrpmodification, in PocketBlacklist, add the following line:
>       ```lua
>          ["spawned_money"] = true,
>       ```
> 
>     * Restart the game
> 
>     * Try to pocket some money. This no longer works because I added it to the blacklist.
> 
> 
> I can only conclude that there is some user error. Without knowing more about your situation, I can only give the following generic advise:
> 
>     * Make sure there is no other addon that sets the PocketBlacklist
> 
>     * Please check your server for errors, either on startup or during gameplay
> 
>     * Make sure the entry in the PocketBlacklist table is correct. Specifically you need to use the classname of an entity. Otherwise it won't work

Yes, sorry I forgot I made this issue. It was in fact an addon I had installed that was outdated and breaking the settings.lua. Thanks for the reply though.
