### ISSUE TITLE
I cant turn off default f4 menu

### ISSUE THREAD

**Issue by Sweeting01** [FPtje/darkrpmodification#182]
Hey, I have just installed a new F4 menu and I want to get rid of the old one, so i thought i would go to the defaults file to check, I set the f4 menu to true and it is still coming up. its not been disabled. I have not altered any base files etc. but I don't know why its not removing the f4 menu. 
![f4](https://github.com/user-attachments/assets/34e3f115-5cf9-42e6-aa5b-473bd05ee877)

sorry if this is no longer supported etc but I would like to have some help if anyone can give me some

**Comment by FPtje** [comment]
Thanks for the report. I just tested this, and disabling the F4 menu in disabled_defaults causes the F4 button to not do anything anymore. That looks like it works like it's supposed to.

> I have just installed a new F4 menu and I want to get rid of the old one

I think there's something wrong with the replacement F4 menu, or the installation of it. Ideally, installing a new F4 menu should just replace the existing one, without you having to worry about going into `disabled_defaults`. I think it's best to verify the installation of your F4 menu, and ask for further help with that specific F4 menu's author/community if that doesn't work.

Since this is not a DarkRP issue, I'm going to close it. Good luck!
